import = ["~/.config/alacritty/themes/themes/smoooooth.toml"]

[font]
normal = {family = "SF Mono", style = "Semibold"}

bold = {style = "Bold"}
italic = {style = "Italic"}
bold_italic = {style = "Bold Italic"}
size = 11.0

[env]

WINIT_X11_SCALE_FACTOR = "1.5"

[window]

dimensions = {columns = 60, lines = 15}
opacity = 0.9
blur = true
dynamic_title = true
